[package]
name = "rz-crypto"
description = "Primitivas criptográficas da Rede Zero (spec/CRYPTOGRAPHY.md)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
rz-codec.workspace = true
ed25519-dalek.workspace = true
blake3.workspace = true
rand_core.workspace = true

[lints]
workspace = true
